
package cl.bice.vida.botonpago.services.notificacion;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "RecaudacionServiceWebServiceService",
                  targetNamespace = "http://webservices.model.integracion.bicevida.cl/",
                  wsdlLocation =
                  "http://canis.bicevida.cl:7777/SviNotificationServiceEjbJar/RecaudacionService?Wsdl#%7Bhttp%3A%2F%2Fwebservices.model.integracion.bicevida.cl%2F%7DRecaudacionServiceWebServiceService")
public class RecaudacionServiceWebServiceService extends Service {

    private final static URL RECAUDACIONSERVICEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException RECAUDACIONSERVICEWEBSERVICESERVICE_EXCEPTION;
    private final static QName RECAUDACIONSERVICEWEBSERVICESERVICE_QNAME =
        new QName("http://webservices.model.integracion.bicevida.cl/", "RecaudacionServiceWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://canis.bicevida.cl:7777/SviNotificationServiceEjbJar/RecaudacionService?wsdl#%7Bhttp%3A%2F%2Fwebservices.model.integracion.bicevida.cl%2F%7DRecaudacionServiceWebServiceService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECAUDACIONSERVICEWEBSERVICESERVICE_WSDL_LOCATION = url;
        RECAUDACIONSERVICEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public RecaudacionServiceWebServiceService() {
        super(__getWsdlLocation(), RECAUDACIONSERVICEWEBSERVICESERVICE_QNAME);
    }

    public RecaudacionServiceWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECAUDACIONSERVICEWEBSERVICESERVICE_QNAME, features);
    }

    public RecaudacionServiceWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, RECAUDACIONSERVICEWEBSERVICESERVICE_QNAME);
    }

    public RecaudacionServiceWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECAUDACIONSERVICEWEBSERVICESERVICE_QNAME, features);
    }

    public RecaudacionServiceWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecaudacionServiceWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RecaudacionServiceWebService
     */
    @WebEndpoint(name = "RecaudacionService")
    public RecaudacionServiceWebService getRecaudacionService() {
        return super.getPort(new QName("http://webservices.model.integracion.bicevida.cl/", "RecaudacionService"),
                             RecaudacionServiceWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecaudacionServiceWebService
     */
    @WebEndpoint(name = "RecaudacionService")
    public RecaudacionServiceWebService getRecaudacionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.model.integracion.bicevida.cl/", "RecaudacionService"),
                             RecaudacionServiceWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECAUDACIONSERVICEWEBSERVICESERVICE_EXCEPTION != null) {
            throw RECAUDACIONSERVICEWEBSERVICESERVICE_EXCEPTION;
        }
        return RECAUDACIONSERVICEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
