
package cl.bicevida.botonpago.ws.cuentainversion;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CuentaDeInversionWebService", targetNamespace = "http://ejb.bicevida.cl/",
                  wsdlLocation =
                  "http://aplicaciones-desa.bicevida.cl/si12/WSSegurosConAhorroJAR/CuentaDeInversion?wsdl#%7Bhttp%3A%2F%2Fejb.bicevida.cl%2F%7DCuentaDeInversionWebService")
public class CuentaDeInversionWebService_Service extends Service {

    private final static URL CUENTADEINVERSIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUENTADEINVERSIONWEBSERVICE_EXCEPTION;
    private final static QName CUENTADEINVERSIONWEBSERVICE_QNAME =
        new QName("http://ejb.bicevida.cl/", "CuentaDeInversionWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://aplicaciones-desa.bicevida.cl/si12/WSSegurosConAhorroJAR/CuentaDeInversion?wsdl#%7Bhttp%3A%2F%2Fejb.bicevida.cl%2F%7DCuentaDeInversionWebService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUENTADEINVERSIONWEBSERVICE_WSDL_LOCATION = url;
        CUENTADEINVERSIONWEBSERVICE_EXCEPTION = e;
    }

    public CuentaDeInversionWebService_Service() {
        super(__getWsdlLocation(), CUENTADEINVERSIONWEBSERVICE_QNAME);
    }

    public CuentaDeInversionWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUENTADEINVERSIONWEBSERVICE_QNAME, features);
    }

    public CuentaDeInversionWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CUENTADEINVERSIONWEBSERVICE_QNAME);
    }

    public CuentaDeInversionWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUENTADEINVERSIONWEBSERVICE_QNAME, features);
    }

    public CuentaDeInversionWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CuentaDeInversionWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CuentaDeInversionWebService
     */
    @WebEndpoint(name = "CuentaDeInversionWebServicePort")
    public CuentaDeInversionWebService getCuentaDeInversionWebServicePort() {
        return super.getPort(new QName("http://ejb.bicevida.cl/", "CuentaDeInversionWebServicePort"),
                             CuentaDeInversionWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentaDeInversionWebService
     */
    @WebEndpoint(name = "CuentaDeInversionWebServicePort")
    public CuentaDeInversionWebService getCuentaDeInversionWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.bicevida.cl/", "CuentaDeInversionWebServicePort"),
                             CuentaDeInversionWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUENTADEINVERSIONWEBSERVICE_EXCEPTION != null) {
            throw CUENTADEINVERSIONWEBSERVICE_EXCEPTION;
        }
        return CUENTADEINVERSIONWEBSERVICE_WSDL_LOCATION;
    }

}
