
package cl.bicevida.botonpago.ws.cuentainversion;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebFault(name = "DatoNuloException", targetNamespace = "http://ejb.bicevida.cl/")
public class DatoNuloException extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private cl.bicevida.botonpago.ws.cuentainversion.types.DatoNuloException faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public DatoNuloException(String message,
                             cl.bicevida.botonpago.ws.cuentainversion.types.DatoNuloException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DatoNuloException(String message, cl.bicevida.botonpago.ws.cuentainversion.types.DatoNuloException faultInfo,
                             Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: cl.bicevida.botonpago.ws.cuentainversion.types.DatoNuloException
     */
    public cl.bicevida.botonpago.ws.cuentainversion.types.DatoNuloException getFaultInfo() {
        return faultInfo;
    }

}
